doctrine:
    dbal:
        driver_class: Doctrine\DBAL\Driver\PDOPgSql\Driver
        host:     '%env(resolve:POSTGRES_HOST)%'
        port:     '%env(resolve:POSTGRES_PORT)%'
        dbname:   '%env(resolve:POSTGRES_DATABASE)%'
        user:     '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
